---
node_exporter_package_name: node_exporter-0.18.1.linux-amd64.tar.gz
node_exporter_unarchive_path: node_exporter-0.18.1.linux-amd64
node_exporter_source_path: /srv/ansible/files/node_exporter
node_exporter_binary_path: /usr/local/bin/
node_exporter_web_listen_address: 0.0.0.0:9100
node_exporter_enabled_collectors: []
node_exporter_disabled_collectors: []
