---
- name: Add jdk package {{ jdk8_package_name }}.
  copy:
    src: /srv/ansible/files/jdk/{{ jdk8_package_name }}
    dest: /tmp/{{ jdk8_package_name }}
    mode: 0755

- name: Install jdk {{ jdk8_package_name }}
  package:
    name: /tmp/{{ jdk8_package_name }}
    state: present
