---
- name: Manage rocketmq bin configs.
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ rocketmq_user }}'
    group: '{{ rocketmq_group }}'
    mode: 0755
  with_items:
    - { src: '{{ rocketmq_cluster_name }}/runserver.sh', dest: '{{ rocketmq_unarchive_path }}/bin/runserver.sh' }
    - { src: '{{ rocketmq_cluster_name }}/runbroker.sh', dest: '{{ rocketmq_unarchive_path }}/bin/runbroker.sh' }

- name: Manage rocketmq conf configs.
  synchronize:
    src: "{{ rocketmq_cluster_name }}/{{ hostname }}/"
    dest: "{{ rocketmq_unarchive_path }}/conf/"
    mode: push
    recursive: yes
    delete: yes
