---
- name: start elasticsearch.
  service:
    name: elasticsearch
    state: started
  when: operate == "start"

- name: stop elasticsearch.
  service:
    name: elasticsearch
    state: stopped
  when: operate == "stop"

- name: restart elasticsearch.
  service:
    name: elasticsearch
    state: restarted
  when: operate == "restart"
