apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acctcenter
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: "/job-admin/toLogin"
spec:
  tls:
  - hosts:
    - acctcenter.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: acctcenter.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: acctcenter
          servicePort: 8080
