apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-web-corp
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - api-web.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: api-web.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: api-web
          servicePort: 8080
