apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: paymonitor
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/app-root: /index.html
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - paymonitor-uat'
spec:
  tls:
  - hosts:
    - paymonitor.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: paymonitor.corp.triThirty.com
    http:
      paths: 
      - path: /jc/ 
        backend:
          serviceName: smonitorsys
          servicePort: 8080
      - path: /
        backend:
          serviceName: fe-monitor
          servicePort: 80
