apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uam
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/app-root: /index.html
spec:
  rules:
  - host: uam.corp.triThirty.com
    http:
      paths: 
      - path: / 
        backend:
          serviceName: uam
          servicePort: 8080

