apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: basic-auth
#    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - www"
spec:
  tls:
  - hosts:
    - www.triThirty.com
    secretName: triThirty.com
  rules:
  - host: www.triThirty.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 8080
