apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cms
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/app-root: /index.html
spec:
  tls:
  - hosts:
    - cms.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: cms.corp.triThirty.com
    http:
      paths: 
      - path: /loanv2 
        backend:
          serviceName: gateway 
          servicePort: 8080
      - path: /
        backend:
          serviceName: react
          servicePort: 80
