apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: credit
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: /easyFlow/index.html
    ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
  - hosts:
    - credit.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: credit.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: credit
          servicePort: 8080
#          serviceContext: /easyFlow/

