apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: usercenterbank
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/app-root: /index.html
spec:
  rules:
  - host: usercenterbank.ali.triThirty.io
    http:
      paths: 
      - path: / 
        backend:
          serviceName: usercenterbank
          servicePort: 8080
