- type: log
  enabled: true
  tail_files: true
  close_*: true
  clean_*: true
  encoding: utf-8
  paths:
    - /opt/app_logs/*/app.log
  scan_frequency: 10s
  exclude_lines: ['HeartBeatCheckController#checkHealth']
  multiline.pattern: '^\d{4}\-\d{2}\-\d{2}'
  multiline.negate: true
  multiline.match: after
  fields:
    logtype: app

- type: log
  enabled: true
  tail_files: true
  close_*: true
  clean_*: true
  encoding: utf-8
  paths:
    - /opt/app_logs/*/api-access.log*
  scan_frequency: 10s
  exclude_lines: ['GET /api/v1/checkHealth']
  multiline.pattern: '^(\[\d{4}\-\d{2}\-\d{2})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
  multiline.negate: true
  multiline.match: after
  fields:
    logtype: api-access

- type: log
  enabled: true
  tail_files: true
  close_*: true
  clean_*: true
  encoding: utf-8
  paths:
    - /opt/app_logs/*/rpc-access.log
  scan_frequency: 10s
  multiline.pattern: '^\[\d{4}\-\d{2}\-\d{2}'
  multiline.negate: true
  multiline.match: after
  fields:
    logtype: rpc-access
