---
- name: Started grafana contailner.
  docker_container:
    name: "{{ grafana_container_name }}"
    state: started
  when: operate == "start"

- name: Stop grafana contailner.
  docker_container:
    name: "{{ grafana_container_name }}"
    state: stopped
  when: operate == "stop"

- name: Delete grafana contailner.
  docker_container:
    name: "{{ grafana_container_name }}"
    state: absent
  when: operate == "delete"
