---
- include: config.yml

- name: Running mongodb container.
  docker_container:
    name: "{{ mongodb_container_name }}"
    image: "{{ mongodb_image_url }}"
    hostname: "{{ inventory_hostname }}"
    user: "{{ container_user }}:{{ container_group }}"
    ports:
    - "{{ mongodb_port }}:27017"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - "{{ mongodb_base_path }}/conf:/etc/mongo"
      - "{{ mongodb_base_path }}/data:/data/db"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongodb_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_passwd }}"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: yes

