apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-metrics
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubelet-metrics
rules:
- apiGroups: [""]
  resources: ["nodes/metrics", "nodes/proxy", "pods", "endpoints", "services", "nodes/*", "pods/*"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /metrics
  - /api
  - /metrics/cadvisor
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubelet-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-metrics
subjects:
- kind: ServiceAccount
  name: kubelet-metrics
  namespace: kube-system
