---
- include: config.yml

- name: Running redis cluster container.
  docker_container:
    name: "{{ redis_container_name }}"
    image: "{{ redis_image_url }}"
    hostname: "{{ inventory_hostname }}"
    ports:
    - "{{ redis_port }}:{{ redis_port }}"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - "{{ redis_base_path }}/conf:/conf"
      - "{{ redis_base_path }}/data:/data"
      - "{{ redis_base_path }}/logs:/logs"
    command:
    - "redis-server /conf/redis.conf"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: yes

