---
- include: config.yml

- name: Running redis sentinel  container.
  docker_container:
    name: "{{ sentinel_container_name }}"
    image: "{{ redis_image_url }}"
    hostname: "{{ inventory_hostname }}"
    ports:
    - "{{ sentinel_port }}:{{ sentinel_port }}"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - "{{ redis_base_path }}/conf:/conf"
      #- "{{ redis_base_path }}/data:/data"
      #- "{{ redis_base_path }}/logs:/logs"
    command:
    - "redis-sentinel /conf/sentinel.conf"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: yes

