---
- name: Ensure zookeeper data dir exists.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0755
  with_items:
    - "{{ zookeeper_base_path }}/data"
    - "{{ zookeeper_base_path }}/conf"
    - "{{ zookeeper_base_path }}/logs"

- name: Configure zookeeper config.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "zoo.cfg.j2", dest: "{{ zookeeper_base_path }}/conf/zoo.cfg" }
    - { src: "log4j.properties.j2", dest: "{{ zookeeper_base_path }}/conf/log4j.properties" }

