---
- name: start kibana.
  service:
    name: kibana
    state: started
  when: operate == "start"

- name: stop kibana.
  service:
    name: kibana
    state: stopped
  when: operate == "stop"

- name: restart kibana.
  service:
    name: kibana
    state: restarted
  when: operate == "restart"
