apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bridge-server-pre-corp
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: bridge-server-pre.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: bridge-server
          servicePort: 8080

