apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cash-fe
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - cash-pre.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: cash-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cash-fe
          servicePort: 80
      - path: /jc
        backend:
          serviceName: k11
          servicePort: 8080
