apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chaseout-fe
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /javaCsApi/(.*)  /$1 break;
      gzip off;
spec:
  tls:
  - hosts:
    - chaseout-pre.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: chaseout-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: chaseout-fe
          servicePort: 80
      - path: /javaCsApi/
        backend:
          serviceName: chaseout-zuul
          servicePort: 8080
