apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chasein-business-pre
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
  - host: chasein-business-pre.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: chasein-business
          servicePort: 8080

