apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: core-out-pre
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: core-out-pre.triThirty.com
    http:
      paths:
      - backend:
          serviceName: core-out
          servicePort: 8080

