apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dubbo-admin-pre-corp
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: dubbo-admin-pre.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: dubbo-admin
          servicePort: 8080

