apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecpouter
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ecpouter-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ecpouter
          servicePort: 8080
