apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka-server
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: eureka-server-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eureka-server
          servicePort: 8080
