apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fenqile
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: fenqile-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fenqile
          servicePort: 8080
