apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haircut-pre
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: /easyFlow/index.html
    ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
  - host: haircut-pre.triThirty.com
    http:
      paths:
      - backend:
          serviceName: haircut
          servicePort: 80

