apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loan-web
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - loan-web-pre.corp.triThirty.com
    secretName: corp.triThirty.com
  rules:
  - host: loan-web-pre.corp.triThirty.com
    http:
      paths:
      - backend:
          serviceName: loan-web
          servicePort: 8080
