apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: overmind-pboc
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: overmind-pboc-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: overmind-pboc
          servicePort: 8080
