apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thrall
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 100;
spec:
  rules:
  - host: thrall-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: thrall
          servicePort: 8080
