apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www-pre
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#  - hosts:
#    - www-pre.triThirty.com
#    secretName: triThirty.com
  rules:
  - host: www-pre.triThirty.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 8080

