apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www
  namespace: triThirty-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.triThirty.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 8080

