apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zuul-server
  namespace: triThirty-pre
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: zuul-server-pre.corp.triThirty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: zuul-server
          servicePort: 8080
