---
- name: Started elasticsearch contailner.
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    state: started
  when: operate == "start"

- name: Stop elasticsearch contailner.
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    state: stopped
  when: operate == "stop"
  
- name: Delete elasticsearch contailner.
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    state: absent
  when: operate == "delete"
